### ISSUE TITLE
accessibilityFeature: unknown

### ISSUE THREAD

**Issue by clapierre** [w3c/a11y-discov-vocab#17]
Should we add "unknown" as an option for accessiblityFeature?
One could just not include accessibilityFeature I assume but wanted to open this up for discussion.

**Comment by mattgarrish** [comment]
If you add "unknown" then technically you could meet the requirements of the EPUB accessibility specification by just saying you don't know if there are any features.

You might as well not bother with the metadata if you're going to say things are unknown. I imagine if someone can't determine if they have any features in their content, they probably aren't implementing this metadata anyway.

**Comment by mattgarrish** [comment]
But you can't conform and be non-compliant. That's why I'm wondering who's going to set this metadata. It has to be someone who's not following the standard but wants to report that they're not following it.

We can add it for general web purposes, but if we add it in then I think we have to be explicit in the epub techniques that this is a non-conforming value, same as I just opened for the "none" value in https://github.com/w3c/epub-specs/issues/2537

**Comment by mattgarrish** [comment]
(Otherwise, I'm not sure why we require metadata in epub when two of the three required fields would let you say you don't know and that's good enough. But this is a topic for another tracker.)

**Comment by gregoriopellegrino** [comment]
There is a use case for the European Accessibility Act to declare the non-conformity (due to different reasons), but it's a wider topic.

**Comment by mattgarrish** [comment]
Closing as this was implemented in https://github.com/w3c/a11y-discov-vocab/pull/70
