### ISSUE TITLE
Discourage schema:accessibilityAPI property?

### ISSUE THREAD

**Issue by LaZay** [w3c/a11y-discov-vocab#30]
Daisy has discouraged the use of `schema:accessibilityAPI` property in the EPUB.
http://kb.daisy.org/publishing/docs/metadata/schema.org/accessibilityAPI
With the true argument that "_The issue of compatibility with operating system accessibility APIs is not applicable to digital publications. The means by which information is conveyed to accessibility APIs is a reading system concern_."

But unfortunatley, one value of `schema:accessibilityAPI  `property does not concern the OS, i.e. the **ARIA** value.
ARIA attributes (such as **@aria-role, @aria-label, @aria-labelledby, @aria-describedby**) must be set inside the EPUB in the first place, so that the reading system may expose them in the ARIA API.
If this ARIA communication mode is not reported anymore anywhere, there is a risk that publishers totally forget about putting any ARIA attributes when needed.

**Comment by mattgarrish** [comment]
The problem, as cited, is that ARIA isn't an accessibility API. It's a set of attributes for exposing information to the platform APIs. This has been confusing people since the metadata was introduced.

We have an issue open to reformulate the value as a feature (see https://github.com/w3c/a11y-discov-vocab/issues/4), so I'm going to close this as a duplicate.
